// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: labels.sql

package database

import (
	"context"
)

const getLabelByName = `-- name: GetLabelByName :one
SELECT id,name FROM labels
WHERE name=$1
`

func (q *Queries) GetLabelByName(ctx context.Context, name string) (Label, error) {
	row := q.db.QueryRowContext(ctx, getLabelByName, name)
	var i Label
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getLabels = `-- name: GetLabels :many
SELECT id,name FROM labels
`

func (q *Queries) GetLabels(ctx context.Context) ([]Label, error) {
	rows, err := q.db.QueryContext(ctx, getLabels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
