// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: labels.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addLabel = `-- name: AddLabel :one
INSERT INTO labels(id,labelName,user_id)
VALUES(
    gen_random_uuid(),
    $1,
    $2
)
RETURNING id, labelname, user_id
`

type AddLabelParams struct {
	Labelname string
	UserID    uuid.UUID
}

func (q *Queries) AddLabel(ctx context.Context, arg AddLabelParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, addLabel, arg.Labelname, arg.UserID)
	var i Label
	err := row.Scan(&i.ID, &i.Labelname, &i.UserID)
	return i, err
}

const getLabels = `-- name: GetLabels :many
SELECT labelName FROM labels
WHERE user_id = $1
`

func (q *Queries) GetLabels(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getLabels, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var labelname string
		if err := rows.Scan(&labelname); err != nil {
			return nil, err
		}
		items = append(items, labelname)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
