// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/google/uuid"
)

type Label struct {
	ID        uuid.UUID
	Labelname string
	UserID    uuid.UUID
}

type Transaction struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	LabelID    uuid.UUID
	ObjectName string
	Cost       float32
}

type User struct {
	ID         uuid.UUID
	Username   string
	Usernumber int32
}
