// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/google/uuid"
)

type Label struct {
	ID   uuid.UUID
	Name string
}

type Transaction struct {
	ID      uuid.UUID
	Object  string
	Cost    float32
	UserID  uuid.UUID
	LabelID uuid.UUID
}

type User struct {
	ID     uuid.UUID
	Name   string
	Number string
}
