// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addTransaction = `-- name: AddTransaction :one
INSERT INTO transactions(id,user_id,label_id,object_name,cost,created_at)
VALUES(
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    NOW()
)
RETURNING id, user_id, label_id, object_name, cost, created_at
`

type AddTransactionParams struct {
	UserID     uuid.UUID
	LabelID    uuid.UUID
	ObjectName string
	Cost       float32
}

func (q *Queries) AddTransaction(ctx context.Context, arg AddTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, addTransaction,
		arg.UserID,
		arg.LabelID,
		arg.ObjectName,
		arg.Cost,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LabelID,
		&i.ObjectName,
		&i.Cost,
		&i.CreatedAt,
	)
	return i, err
}

const getAnalysis = `-- name: GetAnalysis :many
SELECT l.labelName,
    SUM(t.cost)::REAL AS total_cost
FROM transactions as t
INNER JOIN labels as l
ON l.id = t.label_id
WHERE t.user_id = $1 
    AND created_at >= NOW() 
        - $2::int * INTERVAL '1 day'
        - $3::int * INTERVAL '1 month'
        - $4::int * INTERVAL '1 year'
GROUP BY l.id
`

type GetAnalysisParams struct {
	UserID uuid.UUID
	Days   int32
	Months int32
	Years  int32
}

type GetAnalysisRow struct {
	Labelname string
	TotalCost float32
}

func (q *Queries) GetAnalysis(ctx context.Context, arg GetAnalysisParams) ([]GetAnalysisRow, error) {
	rows, err := q.db.QueryContext(ctx, getAnalysis,
		arg.UserID,
		arg.Days,
		arg.Months,
		arg.Years,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAnalysisRow
	for rows.Next() {
		var i GetAnalysisRow
		if err := rows.Scan(&i.Labelname, &i.TotalCost); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactions = `-- name: GetTransactions :many
SELECT t.id,l.labelName,t.object_name,t.cost,t.created_at
FROM transactions as t
INNER JOIN labels as l
on l.id = t.label_id
WHERE t.user_id = $1
`

type GetTransactionsRow struct {
	ID         uuid.UUID
	Labelname  string
	ObjectName string
	Cost       float32
	CreatedAt  sql.NullTime
}

func (q *Queries) GetTransactions(ctx context.Context, userID uuid.UUID) ([]GetTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsRow
	for rows.Next() {
		var i GetTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Labelname,
			&i.ObjectName,
			&i.Cost,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
