// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addRecord = `-- name: AddRecord :one
INSERT INTO transactions(id, object, cost, user_id, label_id)
VALUES(
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4
)
RETURNING id, object, cost, user_id, label_id
`

type AddRecordParams struct {
	Object  string
	Cost    float32
	UserID  uuid.UUID
	LabelID uuid.UUID
}

func (q *Queries) AddRecord(ctx context.Context, arg AddRecordParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, addRecord,
		arg.Object,
		arg.Cost,
		arg.UserID,
		arg.LabelID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Object,
		&i.Cost,
		&i.UserID,
		&i.LabelID,
	)
	return i, err
}
