// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addTransaction = `-- name: AddTransaction :one
INSERT INTO transactions(id,user_id,label_id,object_name,cost,created_at)
VALUES(
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    NOW()
)
RETURNING id, user_id, label_id, object_name, cost, created_at
`

type AddTransactionParams struct {
	UserID     uuid.UUID
	LabelID    uuid.UUID
	ObjectName string
	Cost       float32
}

func (q *Queries) AddTransaction(ctx context.Context, arg AddTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, addTransaction,
		arg.UserID,
		arg.LabelID,
		arg.ObjectName,
		arg.Cost,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LabelID,
		&i.ObjectName,
		&i.Cost,
		&i.CreatedAt,
	)
	return i, err
}

const getAnalysis = `-- name: GetAnalysis :many
SELECT l.labelName,
    SUM(t.cost)::REAL AS total_cost
FROM transactions as t
INNER JOIN labels as l
ON l.id = t.label_id
WHERE t.user_id = $1
GROUP BY l.id
`

type GetAnalysisRow struct {
	Labelname string
	TotalCost float32
}

func (q *Queries) GetAnalysis(ctx context.Context, userID uuid.UUID) ([]GetAnalysisRow, error) {
	rows, err := q.db.QueryContext(ctx, getAnalysis, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAnalysisRow
	for rows.Next() {
		var i GetAnalysisRow
		if err := rows.Scan(&i.Labelname, &i.TotalCost); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
