// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
)

const addUser = `-- name: AddUser :one
INSERT INTO users(id,userName,userNumber)
VALUES(
    gen_random_uuid(),
    $1,
    $2
)
RETURNING id, username, usernumber
`

type AddUserParams struct {
	Username   string
	Usernumber int32
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, addUser, arg.Username, arg.Usernumber)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.Usernumber)
	return i, err
}
